---
title: "競賽說明"
---

<style type="text/css">
h1.title {
    font-size: 45px;
    text-align: center;
    text-decoration: underline;
    text-shadow: 3px 2px 5px blue;
    font-family: "標楷體";
    font-style: italic;
    color:black
}
</style>

<style>
html {
  height: 100%;
}
body{
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
  background-size: cover;
}
  </style>
  


<body>

<br><br><br>

<body width="3000" height="3000" background="background2.jpg">

<div id="main" style="padding:50px;border:10px skyblue dotted;background-color: white;font-size: 20px;"> 
  


<center>✭競賽緣起</center>
<br>
黑客松是黑客+馬拉松（HACK + MARATHON）的組合字，大致上就是幾個人聚在一起以馬拉松的方式進行一段長時間(24小時)的程式設計活動。以軟體、手機應用程式、虛擬實境和雲端服務等技術整合，開發具潛在目標市場包含醫療、環境、教育、娛樂和智慧生活等的資訊科技創新活動。國立臺北大學經濟系今年度首度辦理「第一屆國立臺北大學資料科學應用創新黑客松競賽」活動，期待參賽者能以「技術交流、團隊合作」的精神，在競賽中與實務接軌，發揮無窮的想像力，為新科技帶來不一樣的驚奇！


<br><br><br>

<center>✭競賽資訊</center>
<br>

<ui>

<li>時間：  108年3月16日（六）至3月17日（日）。</li>

<li>地點： 國立臺北大學創業創新中心。</li>

<li>費用： 免費，保證金500元/隊 (將於活動現場全額退回，無出席者恕不退還保證金)。 </li>

<li>費用繳交方式： 線上報名完成後於「收費期間」至「收費地點」繳交。</li>
<li>收費期間：108/2/18～108/2/27，週一～週五，9:00～12:00，13:30～17:00。</li>
<li>收費地點：社會科學院3F 經濟學系辦公室 </li>
<li>將於活動結束後全額退還，無出席者恕不退還保證金 </li>
<li>報名統一採線上申報方式</li>
<li>現場設備： 提供餐飲、電源和無線網路。參賽者請依個人需求攜帶所需設備及相關物品，如筆電、平板及個人睡袋寢具等。 </li>


</ui>
<br><br>

流程：



 <table border="1">
            
<tr>  
  <td>
  時間
              
  </td>
  <td>
  活動項目
              
  </td>
  
</tr>
<tr>
  <td>
  9:00-9:30
              
  </td>
  <td>
  參賽者簽到
             
  </td>
  
</tr>
<tr>
  <td>
  9:30-10:00
              
  </td>
  <td>
  開幕式（公布題目）
            
  </td>
</tr>              
<tr>  
  <td>
  10:00-12:00
              
  </td>
  <td>
 開始coding
              
  </td>
  
</tr>
<tr>  
  <td>
  12:00-13:00
              
  </td>
  <td>
  午餐時間
              
  </td>
  
</tr>
<tr>  
  <td>
  13:00-15:30
              
  </td>
  <td>
  持續coding
              
  </td>
  
</tr>
<tr>  
  <td>
  15:30-16:00
              
  </td>
  <td>
  下午茶時間
              
  </td>
  
</tr>
<tr>  
  <td>
  16:00-18:30
              
  </td>
  <td>
  持續coding
              
  </td>
  
</tr>
<tr>  
  <td>
  18:30-19:30
              
  </td>
  <td>
  晚餐時間
              
  </td>
  
</tr>
<tr>  
  <td>
  19:30-隔日8:00
              
  </td>
  <td>
 持續coding
              
  </td>
  
</tr>
<tr>  
  <td>
  08:00-09:30
              
  </td>
  <td>
  早餐時間
              
  </td>
  
</tr>
<tr>  
  <td>
  9:30-12:30
              
  </td>
  <td>
  各組報告
              
  </td>
  
</tr><tr>  
  <td>
  12:30-13:30
              
  </td>
  <td>
  午餐時間
              
  </td>
  
</tr><tr>  
  <td>
  13:30-14:30
              
  </td>
  <td>
  評審講評
              
  </td>
  
</tr><tr>  
  <td>
  14:30-15:00
              
  </td>
  <td>
  頒獎
              
  </td>
  
</tr><tr>  
  <td>
  15:00-15:10
              
  </td>
  <td>
  閉幕式
              
  </td>
  
</tr>
   
  
   </table>
              
              
           















</div>
  
<br><br><br>

<div id="footer" style="text-align:center; style="margin:0 auto; width:800px;>   
        
        
        
        
  <p class='text3'>
       ✭ 主辦單位：國立臺北大學 經濟學系
  
      ✭贊助單位：英生鋼鐵企業股份有限公司 葉茂泰董事長

      ✭協辦單位：研究發展處 創新創業中心、

                國立臺北大學 資訊工程學系 
 
      
  <br>
  <p class='text4'>
        
 Copyright © 2020 E.Major Taiwan . All rights reserved.
       
  </div>
         
</body>
